#pragma once

#define ILIA_RESULT(code) (((code) << 8) | 0xEE)

#define ILIA_ERR_INVALID_TRAP ILIA_RESULT(1)
#define ILIA_ERR_INVALID_PROCESS_STATE ILIA_RESULT(2)
#define ILIA_ERR_INVALID_THREAD_STATE ILIA_RESULT(3)
#define ILIA_ERR_IO_ERROR ILIA_RESULT(4)
#define ILIA_ERR_NO_SUCH_S_TABLE ILIA_RESULT(5)
#define ILIA_ERR_NON_REENTRANT ILIA_RESULT(6)
#define ILIA_ERR_INVALID_TRAP_STATE ILIA_RESULT(7)
