#pragma once

#define ILIA_RESULT(code) (((code) << 8) | 0xEE)

#define ILIA_ERR_TOO_MANY_PIPES ILIA_RESULT(1)
#define ILIA_ERR_NO_SUCH_PIPE ILIA_RESULT(2)
#define ILIA_ERR_ALREADY_HAS_WRITER ILIA_RESULT(3)
#define ILIA_ERR_ALREADY_HAS_READER ILIA_RESULT(4)
#define ILIA_ERR_COMMAND_REMOVED ILIA_RESULT(5)
#define ILIA_ERR_NAME_TOO_LONG ILIA_RESULT(6)
#define ILIA_ERR_REQUEST_MESSAGE_TOO_LONG ILIA_RESULT(7)
#define ILIA_ERR_INTERFACE_NOT_FOUND ILIA_RESULT(8)
#define ILIA_ERR_TOO_MANY_TARGET_PROCESSES ILIA_RESULT(9)
#define ILIA_ERR_TOO_MANY_PIPES_UNDER_PROCESS ILIA_RESULT(10)
#define ILIA_ERR_COULD_NOT_FIND_HIPC_MANAGER ILIA_RESULT(11)
#define ILIA_ERR_IO_ERROR ILIA_RESULT(12)
#define ILIA_ERR_UNRECOGNIZED_PID ILIA_RESULT(13)
#define ILIA_ERR_ALREADY_INJECTED_PAYLOAD ILIA_RESULT(14)
#define ILIA_ERR_INVALID_PIPE_STATE ILIA_RESULT(15)
